### PR TITLE
Clean up code and add tests

### PR DESCRIPTION
**Pull request by smesseim**
Tests are added to improve test coverage. Deprecated classes are
removed. Anything that had to do with semantic zooming is removed,
because semantic zooming will be built from the ground up again.
Cucumber is added as a dependency, since it is useful for designing
behavior driven tests. All checkstyle warnings are fixed, as well as
code duplication and PMD errors.

### CODE REVIEW

**Comment by aelkhalki** [comment]
Nice cleanup, LGTM.

**Comment by RaviShivam** [comment]
LGTM

**Comment by smesseim** [comment]
Can you re-review this?

**Comment by RaviShivam** [comment]
LGTM

**Comment by tadzjibov** [comment]
LGTM

**Pull request merged**
