### PR TITLE
Aggregate line in graph

### PR DESCRIPTION
**Pull request by smesseim**
The lines in the graph are now aggregated and smoothened.

### CODE REVIEW

**Comment by aelkhalki** [comment]
Is the client side ready for accepting this smoothened version of the graphs?

**Comment by smesseim** [comment]
Yes, the interface is left intact, so the client doesn't have to change.

**Comment by aelkhalki** [comment]
Okay, LGTM!

**Comment by RaviShivam** [comment]
Does the aggregated graph also take into account the main branch (backbone)?

**Comment by RaviShivam** [comment]
Also, you are missing some important javadoc. Can you fix this?

**Comment by smesseim** [comment]
The aggregation itself doesn't, and doesn't need to, because the positioning is separate from the aggregation.

**Comment by RaviShivam** [comment]
Nice, LGTM

**Pull request merged**
