### PR TITLE
Remove unused bubble classes

### PR DESCRIPTION
**Pull request by smesseim**
Some bubble classes have been deprecated, and therefore not been used. They
are removed.

### CODE REVIEW

**Comment by RaviShivam** [comment]
Is the specimen parser really needed now

**Comment by smesseim** [comment]
Yes it is, because the specimen parser works and is tested, and it will be used in a future sprint.

**Comment by RaviShivam** [comment]
Is it however neccessary to put specimen in a database?

**Comment by smesseim** [comment]
Yes because they have too many fields.

**Comment by RaviShivam** [comment]
Great, LGTM

**Comment by tadzjibov** [comment]
LGTM \

**Pull request merged**
